### ISSUE TITLE
ReaderX web font not loading

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/liif-annual-report-2023#10]
*URL tested:* https://liif-annual-report-2023.netlify.app/
Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Ventura&browser=Safari&browser_version=16.5&zoom_to_fit=true&full_screen=true&start=true&url=https://liif-annual-report-2023.netlify.app/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack
Noticed this in Safari, body copy is using a fallback font. Chrome looks okay though!

|Property | Value|
|------------ | -------------|
| Browser | Safari 16.5 |
| Operating System | OS X Ventura |
| Resolution | 1420x928 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8f54b158b1860dec9d14e0f799231dde7457ef01/macven_safari_16.5.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/8f54b158b1860dec9d14e0f799231dde7457ef01/macven_safari_16.5.jpg)

**Comment by andrewmarino** [comment]
@Rapidisimo Hm... the screenshots from Browserstack don't seem to be working?
