### ISSUE TITLE
Progress element not rendering on Safari

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/liif-annual-report-2023#11]
*URL tested:* https://liif-annual-report-2023.netlify.app/
Open [URL](https://live.browserstack.com/dashboard#&start=true&url=https://liif-annual-report-2023.netlify.app/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack
We may need to do an alternative—maybe a div element instead but we can visually hide the progress element for accessibility purposes.

|Property | Value|
|------------ | -------------|
| Browser | Safari 16.5 |
| Operating System | OS X Ventura |
| Resolution | 1420x928 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/00deefad410ac563dcac0c2449c0384c0a6d63fd/macven_safari_16.5.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/00deefad410ac563dcac0c2449c0384c0a6d63fd/macven_safari_16.5.jpg)

**Comment by andrewmarino** [comment]
Seems to render improperly on Firefox as well.

![Screenshot 2024-01-18 at 11 25 43 AM](https://github.com/unitymakesus/liif-annual-report-2023/assets/6686529/dca45948-a2ef-4191-87e6-a53b3bee2eea)

**Comment by andrewmarino** [comment]
@Rapidisimo Ok, let's review together in our check-in this morning.
