### ISSUE TITLE
Hero text position on tablet / mobile

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/liif-annual-report-2023#12]
*URL tested:* https://liif-annual-report-2023.netlify.app/
Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=16.0&device_browser=safari&zoom_to_fit=true&full_screen=true&start=true&url=https://liif-annual-report-2023.netlify.app/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack
On tablet and mobile screens, let's bump the text closer into the image. Add a small amount of space between the "S" character and the edge of the blue background.

|Property | Value|
|------------ | -------------|
| Device | iPad 10th |
| Browser | Tablet_safari |
| Operating System | iOS 16.0 |
| Resolution | 1640x2360 px |
| Screen size | 10.9 in - 9.79 x 7.07 in |
| Viewport | 820 x 1106 px |
| Aspect Ratio | 23 : 16 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/df6c4d14e116a7c5888b85e90bab2f2a96edc55b/realios_iPad_10th.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/df6c4d14e116a7c5888b85e90bab2f2a96edc55b/realios_iPad_10th.jpg)

**Comment by Rapidisimo** [comment]
New direction according to issue #28
