### ISSUE TITLE
Link arrows are rendering as emoji

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/liif-annual-report-2023#15]
*URL tested:* https://liif-annual-report-2023.netlify.app/
Open [URL](https://live.browserstack.com/dashboard#&start=true&url=https://liif-annual-report-2023.netlify.app/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPad 10th |
| Browser | Tablet_safari |
| Operating System | iOS 16.0 |
| Resolution | 1640x2360 px |
| Screen size | 10.9 in - 9.79 x 7.07 in |
| Viewport | 820 x 1106 px |
| Aspect Ratio | 23 : 16 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a52ac19dd7a54fa1ba05802351785584dfee0688/realios_iPad_10th.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/a52ac19dd7a54fa1ba05802351785584dfee0688/realios_iPad_10th.jpg)

**Comment by Rapidisimo** [comment]
@isabisa Huh, that doesn't happen on my safari but I replaced the character (not an emoji) with an html character.

**Comment by Rapidisimo** [comment]
Still not solved.

**Comment by Rapidisimo** [comment]
I wasn't able to find a solution for this yet.

**Comment by Rapidisimo** [comment]
@andrewmarino Is this where we would use an svg instead of characters since they are interpreted differently based on the OS?

**Comment by andrewmarino** [comment]
@Rapidisimo Yes, an SVG would render more consistently than unicode characters.
