### ISSUE TITLE
Reduce heading font size on mobile

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/liif-annual-report-2023#20]
*URL tested:* https://liif-annual-report-2023.netlify.app/
Open [URL](https://live.browserstack.com/dashboard#&start=true&url=https://liif-annual-report-2023.netlify.app/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack
They're 2.25rem at all times, maybe let's aim for something like 1.5rem or so. Will defer to what you think looks best.

|Property | Value|
|------------ | -------------|
| Device | iPhone 13 |
| Browser | Mobile_safari |
| Operating System | iOS 15.0 |
| Resolution | 1170 x 2532 px |
| Screen size | 6.1 in - 5.24 x 2.56 in |
| Viewport | 390 x 664 px |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/7cf704aa1376c8e69db17bbf5555e77da4eb1670/realios_iPhone_13.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/7cf704aa1376c8e69db17bbf5555e77da4eb1670/realios_iPhone_13.jpg)

**Comment by Rapidisimo** [comment]
2.25 -> 2
