### ISSUE TITLE
Table layout on mobile

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/liif-annual-report-2023#27]
*URL tested:* https://liif-annual-report-2023.netlify.app/
Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Samsung+Galaxy+S10&device_browser=chrome&zoom_to_fit=true&full_screen=true&start=true&url=https://liif-annual-report-2023.netlify.app/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack
Things are pretty squished as we know. We could use the same solution we used back on the 2022 report as a potential solution. What do you think?

https://www.liifund.org/impact-report/2022/

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S10 |
| Browser | Mobile_chrome |
| Operating System | Android 9.0 |
| Resolution | 1440 x 3040 px |
| Screen size | 6.4 in - 5.51 x 2.61 in |
| Viewport | 412 x 722 px |
| Aspect Ratio | 19 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5f0e690fdbcca8ea99e63cc95bdd7667fd7a8b20/realdroid_Samsung_Galaxy_S10.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5f0e690fdbcca8ea99e63cc95bdd7667fd7a8b20/realdroid_Samsung_Galaxy_S10.jpg)

**Comment by Rapidisimo** [comment]
> Also, let's add a $ symbol before each dollar value in the table cells.

@andrewmarino Client doesn't want dollar signs per final content doc.

**Comment by andrewmarino** [comment]
@Rapidisimo Ah, gotcha. I find it confusing but that's what they want I guess—thank you for the note from the client.
